version: 1.2
workflows:
  - name: rotahost-eqtl
    subclass: WDL
    primaryDescriptorPath: /terra/rotahost_eqtl.wdl
    testParameterFiles:
      - /terra/test_params_toytest.json
    publish: true
    topic: "RotaHost sc-eQTL + sc-pQTL pipeline (sc-eQTLGen WG3 approach). Guzman, Triana et al."
    latestTagAsDefault: true
